/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.arc_connects.api.user;

import com.arc_connects.api.user.request.CreateUserRequest;
import com.arc_connects.api.common.response.ErrorResponse;
import com.arc_connects.api.user.request.UpdateUserRequest;
import com.arc_connects.api.user.response.UserPageResponse;
import com.arc_connects.api.user.response.UserResponse;
import com.arc_connects.api.user.response.UserStatus;
import com.arc_connects.api.user.response.ValidationErrorResponse;
import com.arc_connects.api.common.ApiUtil;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-07-26T10:06:49.238047805+09:00[Asia/Tokyo]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "user", description = "the user API")
public interface UserApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/users : 新規ユーザーを作成
     * 新しいユーザーを作成します。 メールアドレスは一意である必要があります。 
     *
     * @param createUserRequest 作成するユーザー情報 (required)
     * @return ユーザー作成成功 (status code 201)
     *         or リクエストボディが不正 (status code 400)
     *         or メールアドレスが既に使用されている (status code 409)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "createUser",
        summary = "新規ユーザーを作成",
        description = "新しいユーザーを作成します。 メールアドレスは一意である必要があります。 ",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "201", description = "ユーザー作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストボディが不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "メールアドレスが既に使用されている", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<UserResponse> createUser(
        @Parameter(name = "CreateUserRequest", description = "作成するユーザー情報", required = true) @Valid @RequestBody CreateUserRequest createUserRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2024-01-15T10:30:00Z\", \"role\" : \"USER\", \"address\" : { \"prefecture\" : \"東京都\", \"city\" : \"新宿区\", \"postalCode\" : \"1234567\", \"addressLine\" : \"新宿1-1-1 新宿ビル101\" }, \"lastLoginAt\" : \"2024-01-25T09:15:00Z\", \"phone\" : \"09012345678\", \"name\" : \"田中太郎\", \"id\" : 1, \"department\" : \"開発部\", \"birthDate\" : \"1990-04-15\", \"email\" : \"tanaka@example.com\", \"status\" : \"ACTIVE\", \"updatedAt\" : \"2024-01-20T14:45:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/users\", \"validationErrors\" : [ { \"field\" : \"email\", \"message\" : \"正しいメールアドレス形式で入力してください\", \"rejectedValue\" : \"invalid-email\" }, { \"field\" : \"email\", \"message\" : \"正しいメールアドレス形式で入力してください\", \"rejectedValue\" : \"invalid-email\" } ], \"error\" : \"Validation failed\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/users/{id} : ユーザーを削除
     * 指定されたIDのユーザーを削除します。 物理削除ではなく、論理削除（ステータスをINACTIVEに変更）を行います。 
     *
     * @param id 削除対象のユーザーID (required)
     * @return ユーザー削除成功（レスポンスボディなし） (status code 204)
     *         or 指定されたユーザーが見つからない (status code 404)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "deleteUser",
        summary = "ユーザーを削除",
        description = "指定されたIDのユーザーを削除します。 物理削除ではなく、論理削除（ステータスをINACTIVEに変更）を行います。 ",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "204", description = "ユーザー削除成功（レスポンスボディなし）"),
            @ApiResponse(responseCode = "404", description = "指定されたユーザーが見つからない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/users/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> deleteUser(
        @Min(1L) @Parameter(name = "id", description = "削除対象のユーザーID", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/users/{id} : ユーザー詳細を取得
     * 指定されたIDのユーザー詳細情報を取得します。 存在しないIDが指定された場合は404エラーを返します。 
     *
     * @param id ユーザーID (required)
     * @return ユーザー詳細取得成功 (status code 200)
     *         or 指定されたユーザーが見つからない (status code 404)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "getUserById",
        summary = "ユーザー詳細を取得",
        description = "指定されたIDのユーザー詳細情報を取得します。 存在しないIDが指定された場合は404エラーを返します。 ",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ユーザー詳細取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "指定されたユーザーが見つからない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/users/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<UserResponse> getUserById(
        @Min(1L) @Parameter(name = "id", description = "ユーザーID", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2024-01-15T10:30:00Z\", \"role\" : \"USER\", \"address\" : { \"prefecture\" : \"東京都\", \"city\" : \"新宿区\", \"postalCode\" : \"1234567\", \"addressLine\" : \"新宿1-1-1 新宿ビル101\" }, \"lastLoginAt\" : \"2024-01-25T09:15:00Z\", \"phone\" : \"09012345678\", \"name\" : \"田中太郎\", \"id\" : 1, \"department\" : \"開発部\", \"birthDate\" : \"1990-04-15\", \"email\" : \"tanaka@example.com\", \"status\" : \"ACTIVE\", \"updatedAt\" : \"2024-01-20T14:45:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/users : ユーザー一覧を取得
     * 登録されているユーザーの一覧を取得します。 ページネーション、フィルタリング、ソートに対応しています。 
     *
     * @param page ページ番号（0から開始） (optional, default to 0)
     * @param size 1ページあたりの件数 (optional, default to 20)
     * @param sort ソート条件（カンマ区切りで複数指定可能） 例: name,asc または email,desc  (optional)
     * @param name 名前による部分一致検索 (optional)
     * @param email メールアドレスによる部分一致検索 (optional)
     * @param status ユーザーステータスによるフィルタ (optional)
     * @return ユーザー一覧取得成功 (status code 200)
     *         or リクエストパラメータが不正 (status code 400)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "getUsers",
        summary = "ユーザー一覧を取得",
        description = "登録されているユーザーの一覧を取得します。 ページネーション、フィルタリング、ソートに対応しています。 ",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ユーザー一覧取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserPageResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストパラメータが不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/users",
        produces = { "application/json" }
    )
    
    default ResponseEntity<UserPageResponse> getUsers(
        @Min(0) @Parameter(name = "page", description = "ページ番号（0から開始）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(1) @Max(100) @Parameter(name = "size", description = "1ページあたりの件数", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "sort", description = "ソート条件（カンマ区切りで複数指定可能） 例: name,asc または email,desc ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) String sort,
        @Parameter(name = "name", description = "名前による部分一致検索", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name,
        @Parameter(name = "email", description = "メールアドレスによる部分一致検索", in = ParameterIn.QUERY) @Valid @RequestParam(value = "email", required = false) String email,
        @Parameter(name = "status", description = "ユーザーステータスによるフィルタ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) UserStatus status
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"number\" : 0, \"last\" : false, \"numberOfElements\" : 20, \"size\" : 20, \"totalPages\" : 8, \"pageable\" : { \"paged\" : true, \"pageNumber\" : 0, \"offset\" : 0, \"pageSize\" : 20, \"unpaged\" : false, \"sort\" : { \"unsorted\" : false, \"sorted\" : true, \"empty\" : false } }, \"sort\" : { \"unsorted\" : false, \"sorted\" : true, \"empty\" : false }, \"content\" : [ { \"createdAt\" : \"2024-01-15T10:30:00Z\", \"role\" : \"USER\", \"address\" : { \"prefecture\" : \"東京都\", \"city\" : \"新宿区\", \"postalCode\" : \"1234567\", \"addressLine\" : \"新宿1-1-1 新宿ビル101\" }, \"lastLoginAt\" : \"2024-01-25T09:15:00Z\", \"phone\" : \"09012345678\", \"name\" : \"田中太郎\", \"id\" : 1, \"department\" : \"開発部\", \"birthDate\" : \"1990-04-15\", \"email\" : \"tanaka@example.com\", \"status\" : \"ACTIVE\", \"updatedAt\" : \"2024-01-20T14:45:00Z\" }, { \"createdAt\" : \"2024-01-15T10:30:00Z\", \"role\" : \"USER\", \"address\" : { \"prefecture\" : \"東京都\", \"city\" : \"新宿区\", \"postalCode\" : \"1234567\", \"addressLine\" : \"新宿1-1-1 新宿ビル101\" }, \"lastLoginAt\" : \"2024-01-25T09:15:00Z\", \"phone\" : \"09012345678\", \"name\" : \"田中太郎\", \"id\" : 1, \"department\" : \"開発部\", \"birthDate\" : \"1990-04-15\", \"email\" : \"tanaka@example.com\", \"status\" : \"ACTIVE\", \"updatedAt\" : \"2024-01-20T14:45:00Z\" } ], \"first\" : true, \"totalElements\" : 150, \"empty\" : false }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/users/{id} : ユーザー情報を更新
     * 指定されたIDのユーザー情報を更新します。 部分更新には対応しておらず、全項目の指定が必要です。 
     *
     * @param id 更新対象のユーザーID (required)
     * @param updateUserRequest 更新するユーザー情報 (required)
     * @return ユーザー更新成功 (status code 200)
     *         or リクエストボディが不正 (status code 400)
     *         or 指定されたユーザーが見つからない (status code 404)
     *         or メールアドレスが既に他のユーザーに使用されている (status code 409)
     *         or サーバー内部エラー (status code 500)
     */
    @Operation(
        operationId = "updateUser",
        summary = "ユーザー情報を更新",
        description = "指定されたIDのユーザー情報を更新します。 部分更新には対応しておらず、全項目の指定が必要です。 ",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ユーザー更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストボディが不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "指定されたユーザーが見つからない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "メールアドレスが既に他のユーザーに使用されている", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバー内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/users/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<UserResponse> updateUser(
        @Min(1L) @Parameter(name = "id", description = "更新対象のユーザーID", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "UpdateUserRequest", description = "更新するユーザー情報", required = true) @Valid @RequestBody UpdateUserRequest updateUserRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2024-01-15T10:30:00Z\", \"role\" : \"USER\", \"address\" : { \"prefecture\" : \"東京都\", \"city\" : \"新宿区\", \"postalCode\" : \"1234567\", \"addressLine\" : \"新宿1-1-1 新宿ビル101\" }, \"lastLoginAt\" : \"2024-01-25T09:15:00Z\", \"phone\" : \"09012345678\", \"name\" : \"田中太郎\", \"id\" : 1, \"department\" : \"開発部\", \"birthDate\" : \"1990-04-15\", \"email\" : \"tanaka@example.com\", \"status\" : \"ACTIVE\", \"updatedAt\" : \"2024-01-20T14:45:00Z\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/users\", \"validationErrors\" : [ { \"field\" : \"email\", \"message\" : \"正しいメールアドレス形式で入力してください\", \"rejectedValue\" : \"invalid-email\" }, { \"field\" : \"email\", \"message\" : \"正しいメールアドレス形式で入力してください\", \"rejectedValue\" : \"invalid-email\" } ], \"error\" : \"Validation failed\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/api/chat\", \"error\" : \"Invalid request format\", \"timestamp\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
